import GNB from "@/components/common/GNB";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Do it!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-gray-50 bg-slate-100 font-sans antialiased">
        <GNB />
        <main className="mx-auto w-full max-w-[1200px] sm:px-4 md:px-6 lg:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
